### ISSUE TITLE
Does this support polyenergetic x-ray scan data decomposition?

### ISSUE THREAD

**Issue by SpencerXia** [gjadick/dex-ct-sim#2]
Thanks

**Comment by gjadick** [comment]
Yes! The functions for this are in matdecomp.py. The function `do_matdecomp_gn` uses an iterative Gauss-Newton method to do material decomposition in the sinogram domain while accounting for polyenergetic spectrum and energy-dependent detector response. The polyenergetic spectrum info is in the arguments `spec1` and `spec2`, which are instances of the Spectrum class (defined in system.py). Currently I have a lot of hardcoding in the Spectrum definition, so if you want to plug in your own polyenergic spectra, you might need to modify it. The two main things you'll need are an array of energies E and the raw intensities I0_raw. 

Happy to clarify anything else if you want to test out your own polyenergetic data.

**Comment by gjadick** [comment]
[This poster](https://www.researchgate.net/profile/David-Rigie/publication/283643470_poster/links/564224fd08aebaaea1f8bed7/poster.pdf) describes the material decomposition method in more detail.

**Comment by SpencerXia** [comment]
Thanks for your quick feedback, Gia.
I have a question from the practical side, with simulation,  spectrum of X-ray source, detector response  of  each mono-kev in the spectrum is known. How to do this in actual CT data acquisition?  Is there practical method to measure this? Especailly for energetic integrate detector.

**Comment by gjadick** [comment]
I'm more on the simulation side, so I am not certain about how to measure each energy bin's response on a real detector. I imagine different CT vendors have their way of doing this though. To simulate however, you could choose a typical detector material and thickness (t) and then use the [NIST database of attenuation coefficients](https://physics.nist.gov/PhysRefData/XrayMassCoef/tab3.html) (mu) to compute the % photons stopped by the detector = 1 - exp(mu*t).

**Comment by SpencerXia** [comment]
Thanks. Gia.
